name: HTML validation

on:
  push:
    branches: ["master"]
    paths: ["index.html"]
  pull_request:
    paths: ["index.html"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML (W3C vnu)
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: true
